### ISSUE TITLE
Error starting App

### ISSUE THREAD

**Issue by Torbilicious** [axilis/typescript-fullstack#2]
When starting with `yarn rstart` I get the following error: 
```
./react/src/containers/Login/index.tsx
(48,5): error TS2605: JSX element type 'Link' is not a constructor function for JSX elements.
```

Is this a mistake on my side, or an actual error?

**Comment by Soudny** [comment]
This looks like an issue with running `npm install` command, and, unfortunately, I am unable to reproduce it. 

Would you mind trying to run `npm install` or `yarn` again and see if that works. If not, please let me know which node version you are trying to run the project on so that I can try to recreate the issue more accurately.

**Comment by djambrecina** [comment]
I can reproduce the issue. I cloned the repository, ran `npm install` and after starting with `npm run rstart` I got the same error.

**Comment by Soudny** [comment]
Looks like the issue was with `react-router-dom` typings and how they didn't match the necessary typings of the `react-router-dom` package.

I have fixed and pushed the issue, so running new `npm install` and `npm run rstart` command should do the trick
